---
abstract: 'REPL when your application throws errors or warnings'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Plack::Middleware::REPL
name: Plack-Middleware-REPL
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp::REPL: 0.15
  Plack: 0.9977
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/miyagawa/Plack-Middleware-REPL.git
version: 0.01
